module.exports = {
  minLength: 10,
  requireUppercase: true,
  requireLowercase: true,
  requireNumbers: true,
  requireSpecialChars: true,
  passwordHistory: 3,
  commonWords: [
    "password",
    "welcome",
    "123456",
    "admin",
    "qwerty",
    "letmein",
    "monkey",
    "abc123",
    "football",
    "iloveyou",
    "sunshine",
    "princess",
    "dragon",
    "administrator",
    "shadow",
  ],
  maxLoginAttempts: 3,
};
